import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import { Grechen_Fuemen } from "next/font/google";
import "./globals.css";

// Initialize Grechen Fuemen (without `variable` since it doesn't support it)
const grechenFuemen = Grechen_Fuemen({
  subsets: ["latin"],
  weight: "400", // Only one available weight for Grechen Fuemen
});

// Initialize Geist Mono with a CSS variable
const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistMono.variable} font-[${grechenFuemen.className}] antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
